---
resources:
  - name: project-source
    type: git
    icon: github-circle
    source:
      uri: {{project-git-source}}

jobs:
  - name: job
    public: true
    plan:
      - get: project-source
        trigger: true
      - task: list-files
        file: project-source/ci/tasks/node-install
        on_success:
          task: notify-slack
          file: project-source/ci/tasks/notify-slack
          params:
            message: "Experiment passed first step"
        on_failure:
          task: notify-slack
          file: project-source/ci/tasks/notify-slack
          params:
            message: "Experiment passed first step"