---
resources:
  - name: concourse-experiment
    type: git
    icon: github-circle
    source:
      uri: https://github.com/martinbjorkman/concourse-experiment

jobs:
  - name: job
    public: true
    plan:
      - get: concourse-experiment
        trigger: true
      - task: list-files
        config:
          inputs:
            - name: concourse-experiment
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: ls
            args: ["-la", "./concourse-experiment"]