---
resource_types:

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:
- name: project-source
  type: git
  icon: github-circle
  source:
    uri: {{project-git-source}}

- name: notify
  type: slack-notification
  source:
    url: {{slack-web-hook}}

- name: node-image
  type: docker-image
  source:
    repository: node
    tag: {{base-image-tag}}

jobs:
- name: verify-repository
  plan:
  - get: project-source
    trigger: true
  - get: node-image
    params: {save: true}
  - task: install
    file: project-source/ci/tasks/node-install.yml
    image: node-image
    on_success:
      do:
      - put: notify
        params:
          text: "Experiment passed dependency installation"
    on_failure:
      do:
      - put: notify
        params:
          text: "Experiment failed dependency installation"
  # - task: unit-test
  #   image: node-image
  #   config:
  #     inputs:
  #     - name: project-source
  #     platform: linux
  #     run:
  #       path: npm
  #       args: ["test", "./project-source"]
  #   on_success:
  #     do:
  #     - put: notify
  #       params:
  #         text: "Experiment passed unit tests"
  #   on_failure:
  #     do:
  #     - put: notify
  #       params:
  #         text: "Experiment failed unit tests"
