---
resource_types:
- name: pull-request
  type: registry-image
  source: {repository: teliaoss/github-pr-resource}

resources:
- name: project-pr
  type: pull-request
  icon: source-pull
  source:
    repository: martinbjorkman/concourse-experiment
    access_token: ((pull_requests_access_token))

- name: node-image
  type: registry-image
  icon: docker
  source: { repository: node, tag: "10.16-alpine"}

jobs:
- name: unit-test
  on_failure:
    put: project-pr
    inputs: [project-pr]
    params: {path: project-pr, status: failure, context: unit-test}
  on_success:
    put: project-pr
    inputs: [project-pr]
    params: {path: project-pr, status: success, context: unit-test}
  plan:
  - in_parallel:
    - get: project-pr
      trigger: true
      version: every
    - get: node-image
  - put: project-pr
    inputs: [project-pr]
    params: {path: project-pr, status: pending, context: unit-test}
    get_params: {list_changed_files: true}
  - task: node-test
    file: project-pr/ci/tasks/node-test.yml
    input_mapping: {project: project-pr}