---
platform: linux
inputs:
- name: project-source
image_resource:
  type: docker-image
  source:
    repository: node
    tag: {{base-image-tag}}
run:
  path: npm
  args: ["install", "./project-source"]
run:
  path: project-source/ci/scripts/node-build.sh
