---
platform: linux

inputs:
- name: project-source

outputs:
- name: project-with-dependencies

image_resource:
  type: docker-image
  source:
    repository: node
    tag: {{base-image-tag}}

run:
  path: npm
  args: ["install", "./project-source"]
